apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app
  labels:
    app: app
spec:
  replicas: 1 # As specified, can be scaled
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: "placeholder-atomic-app:latest" # Consistent placeholder name
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000 # Should match PORT in ConfigMap
              protocol: TCP
          envFrom:
            - secretRef:
                name: app-secret
            - configMapRef:
                name: app-configmap
          # Explicitly map Dockerfile ARGs from app-secret to ensure they are available
          # with their original names if the application's build or runtime expects them directly,
          # not just as NEXT_PUBLIC_ variables.
          env:
            - name: HASURA_GRAPHQL_ADMIN_SECRET # ARG from Dockerfile
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: HASURA_GRAPHQL_ADMIN_SECRET
            - name: GOOGLE_CLIENT_ID_ATOMIC_WEB # ARG from Dockerfile
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: GOOGLE_CLIENT_ID_ATOMIC_WEB
            - name: GOOGLE_CLIENT_SECRET_ATOMIC_WEB # ARG from Dockerfile
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: GOOGLE_CLIENT_SECRET_ATOMIC_WEB
            - name: ZOOM_IV_FOR_PASS # ARG from Dockerfile
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: ZOOM_IV_FOR_PASS
            - name: ZOOM_PASS_KEY # ARG from Dockerfile
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: ZOOM_PASS_KEY
            # Note: The ConfigMap contains NEXT_PUBLIC_GOOGLE_CLIENT_ID_ATOMIC_WEB.
            # If this should be the *same value* as the ARG GOOGLE_CLIENT_ID_ATOMIC_WEB from the secret,
            # then the ConfigMap entry is redundant, and the Next.js app should be configured
            # to use GOOGLE_CLIENT_ID_ATOMIC_WEB (from secret) for its NEXT_PUBLIC_GOOGLE_CLIENT_ID_ATOMIC_WEB build process.
            # Or, this env var can be set here to override the ConfigMap one:
            # - name: NEXT_PUBLIC_GOOGLE_CLIENT_ID_ATOMIC_WEB
            #   valueFrom:
            #     secretKeyRef:
            #       name: app-secret
            #       key: GOOGLE_CLIENT_ID_ATOMIC_WEB
            # For now, assuming the explicit ARG env vars are needed by the build/runtime,
            # and NEXT_PUBLIC_ vars in configmap are for client-side values (which might be same or different).

          readinessProbe:
            httpGet:
              path: / # Check root path, or a specific health endpoint
              port: http # Port 3000
            initialDelaySeconds: 10 # Allow time for Next.js server to start
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
