apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: app
type: Opaque
data:
  # Secrets derived from Dockerfile ARGs for the 'app' service
  HASURA_GRAPHQL_ADMIN_SECRET: bXlhZG1pbnNlY3JldGtleQ== # "myadminsecretkey" (Ensure this matches Hasura's actual admin secret if used at runtime)

  GOOGLE_CLIENT_ID_ATOMIC_WEB: cGxhY2Vob2xkZXJfdmFsdWU= # "placeholder_value"
  GOOGLE_CLIENT_SECRET_ATOMIC_WEB: cGxhY2Vob2xkZXJfdmFsdWU= # "placeholder_value"

  ZOOM_IV_FOR_PASS: cGxhY2Vob2xkZXJfdmFsdWU= # "placeholder_value"
  ZOOM_PASS_KEY: cGxhY2Vob2xkZXJfdmFsdWU= # "placeholder_value"

  # Add any other sensitive runtime environment variables the 'app' service might need.
  # For example, if it directly calls a service requiring an API key not covered by NEXT_PUBLIC_ variables.
  # INTERNAL_SERVICE_API_KEY: cGxhY2Vob2xkZXJfdmFsdWU=
