apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: app
type: Opaque
data:
  # Hasura Admin Secret (if direct privileged access is needed by the app, though unlikely for a frontend)
  # It's listed as an ARG, so including it. Could be for build-time operations.
  HASURA_GRAPHQL_ADMIN_SECRET: bXlhZG1pbnNlY3JldGtleQ== # "myadminsecretkey" (ensure this matches Hasura's actual admin secret)

  # Google OAuth Client for Atomic Web (assuming 'app' is the atomic-app)
  GOOGLE_CLIENT_ID_ATOMIC_WEB: cGxhY2Vob2xkZXJfdmFsdWU= # "placeholder_value"
  GOOGLE_CLIENT_SECRET_ATOMIC_WEB: cGxhY2Vob2xkZXJfdmFsdWU= # "placeholder_value"

  # Zoom Encryption Keys (if used by frontend, though more typical in backend)
  # Listed as ARGs, so including them.
  ZOOM_IV_FOR_PASS: cGxhY2Vob2xkZXJfdmFsdWU=
  ZOOM_PASS_KEY: cGxhY2Vob2xkZXJfdmFsdWU=

  # Any other sensitive ARGs or runtime needs for the app service
  # For example, if the app uses its own session secret or API keys for other services
  APP_SPECIFIC_API_KEY: cGxhY2Vob2xkZXJfdmFsdWU= # Example if app needs its own API key for something
