apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app
  labels:
    app: app
spec:
  type: ClusterIP # Internal service; will be exposed via Ingress externally
  selector:
    app: app # Selects the app pods
  ports:
    - name: http
      protocol: TCP
      port: 3000       # Port the service will listen on
      targetPort: http # Matches the 'http' port name in the Deployment's podSpec (containerPort 3000)
