# deploy/kubernetes/overlays/azure/patches/traefik-service-azure-annotations.yaml
# This patch adds Azure Load Balancer specific annotations to the Traefik service.
# It assumes the base Traefik service is named 'traefik' and is in the 'traefik-ingress' namespace,
# and is of type LoadBalancer.

apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik-ingress # Common namespace for Traefik, adjust if different in your base
  annotations:
    # --- Azure Load Balancer Configuration Annotations ---

    # Specify the SKU for the Azure Load Balancer. "Standard" is recommended for production.
    # "Basic" SKU has limitations (e.g., no availability zones, no health probes on specific paths).
    service.beta.kubernetes.io/azure-load-balancer-sku: "Standard"

    # Specify if the load balancer is internet-facing or internal.
    # "false" means internet-facing (public). "true" would make it internal.
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"

    # --- Health Probe Configuration ---
    # Define the request path for the health probe. Traefik typically has a /ping endpoint for health checks.
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/ping"

    # Specify which port on the service the health probe should target.
    # This should be the port number that corresponds to a Traefik entrypoint where /ping is available.
    # Assuming Traefik's 'web' entrypoint (port 80) also serves the /ping endpoint for LB health checks.
    service.beta.kubernetes.io/azure-load-balancer-health-probe-port: "80"

    # --- Idle Timeout Configuration ---
    # Configure the idle timeout for TCP and HTTP connections, in minutes. Default is 4 minutes. Max is 30.
    service.beta.kubernetes.io/azure-load-balancer-idle-timeout-in-minutes: "30"

    # --- Optional: Use a pre-existing Public IP Address ---
    # If you have a static public IP address resource created in Azure that you want to assign to the Load Balancer.
    # The Public IP must be of the same SKU (Standard) and in the same region as the AKS cluster.
    #
    # 1. Name of the Public IP Address resource in Azure:
    # service.beta.kubernetes.io/azure-pip-name: "your-existing-public-ip-name"
    #
    # 2. Resource group of the Public IP Address (if different from the cluster's node resource group - MC_*):
    #    Typically, for auto-association, it's expected to be in the node resource group or explicitly specified.
    # service.beta.kubernetes.io/azure-load-balancer-resource-group: "your-public-ip-resource-group"
    # (More commonly, the public IP is created in the node resource group if managed by AKS LB integration)

    # --- Optional: DNS Label Name ---
    # Creates a DNS A record for the Load Balancer's public IP (e.g., mytraefik.eastus.cloudapp.azure.com).
    # The DNS label must be unique within its Azure region.
    # service.beta.kubernetes.io/azure-dns-label-name: "your-traefik-dns-label"

    # --- Optional: Enable PROXY protocol (v2) ---
    # If Traefik is configured to use PROXY protocol to receive client IP information.
    # Both Traefik and the Azure LB need to be configured for this.
    # service.beta.kubernetes.io/azure-load-balancer-enable-proxy-protocol: "true"

    # --- Optional: Specify number of health probe retries ---
    # service.beta.kubernetes.io/azure-load-balancer-health-probe-num-of-probes: "2" # Default is 2

    # --- Optional: Specify health probe interval ---
    # service.beta.kubernetes.io/azure-load-balancer-health-probe-interval: "5" # Default is 5 seconds

    # Note: Ensure the Kubernetes cloud provider integration with Azure is correctly configured
    # in your AKS cluster for these annotations to take effect.
    # The specific annotations available and their behavior can depend on the version
    # of the Kubernetes Azure cloud provider and AKS. Always refer to official Azure Kubernetes Service (AKS) documentation.
