# deploy/kubernetes/overlays/aws/patches/update-secret-references.yaml
# This file contains strategic merge patches to update secret references.

# --- Patch for Functions Deployment ---
# Base 'functions-secret' -> SPC 'functions-app-credentials'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: functions
  namespace: functions
spec:
  template:
    spec:
      containers:
      - name: functions
        envFrom: # Replaces the existing envFrom array
          - secretRef:
              name: functions-app-credentials # Patched
          - configMapRef: # Must re-state if present in base
              name: functions-configmap

# --- Patch for App Deployment ---
# Base 'app-secret' -> SPC 'app-credentials'
# This patches both the 'envFrom' and specific 'env' vars that referenced 'app-secret'.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app
spec:
  template:
    spec:
      containers:
      - name: app
        envFrom: # Replaces the 'envFrom' part
          - secretRef:
              name: app-credentials # Patched
          - configMapRef:
              name: app-configmap
        env: # Attempts to merge/replace individual env vars by name
          - name: HASURA_GRAPHQL_ADMIN_SECRET
            valueFrom:
              secretKeyRef:
                name: app-credentials # Patched
                key: HASURA_GRAPHQL_ADMIN_SECRET
          - name: GOOGLE_CLIENT_ID_ATOMIC_WEB
            valueFrom:
              secretKeyRef:
                name: app-credentials # Patched
                key: GOOGLE_CLIENT_ID_ATOMIC_WEB
          - name: GOOGLE_CLIENT_SECRET_ATOMIC_WEB
            valueFrom:
              secretKeyRef:
                name: app-credentials # Patched
                key: GOOGLE_CLIENT_SECRET_ATOMIC_WEB
          - name: ZOOM_IV_FOR_PASS
            valueFrom:
              secretKeyRef:
                name: app-credentials # Patched
                key: ZOOM_IV_FOR_PASS
          - name: ZOOM_PASS_KEY
            valueFrom:
              secretKeyRef:
                name: app-credentials # Patched
                key: ZOOM_PASS_KEY
          # Any other env vars from base, not listed here, should remain untouched by this 'env:' block.
          # Only those listed are targeted for update by Kustomize's strategic merge on named env vars.

# --- Patch for Handshake Deployment ---
# Base 'handshake-secret' -> SPC 'handshake-credentials'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: handshake
  namespace: handshake
spec:
  template:
    spec:
      containers:
      - name: handshake
        envFrom:
          - secretRef:
              name: handshake-credentials # Patched
          - configMapRef:
              name: handshake-configmap

# --- Patch for OAuth Deployment ---
# Base 'oauth-secret' -> SPC 'oauth-credentials'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth
  namespace: oauth
spec:
  template:
    spec:
      containers:
      - name: oauth
        envFrom:
          - secretRef:
              name: oauth-credentials # Patched
          - configMapRef:
              name: oauth-configmap

# --- Patch for PostgreSQL StatefulSet ---
# Base 'postgres-secret' -> SPC 'postgres-credentials'
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres
spec:
  template:
    spec:
      containers:
      - name: postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials # Patched
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials # Patched
              key: POSTGRES_PASSWORD
        # POSTGRES_DB was a direct value in base, not from secret, so no change needed here.
        # PGDATA was also direct value.

# --- Patch for MinIO Deployment ---
# Base 'minio-secret' -> SPC 'minio-credentials'
# Keys in minio-credentials are MINIO_ROOT_USER, MINIO_ROOT_PASSWORD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: minio
spec:
  template:
    spec:
      containers:
      - name: minio
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-credentials # Patched
              key: MINIO_ROOT_USER # Key in the SPC-synced K8s Secret
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-credentials # Patched
              key: MINIO_ROOT_PASSWORD # Key in the SPC-synced K8s Secret

# --- Patch for Supertokens Deployment ---
# Base 'supertokens-db-secret' -> SPC 'supertokens-credentials'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supertokens-core
  namespace: supertokens
spec:
  template:
    spec:
      containers:
      - name: supertokens
        env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: supertokens-credentials # Patched
              key: DB_USER # Assuming key in new secret is DB_USER
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: supertokens-credentials # Patched
              key: DB_PASSWORD # Assuming key in new secret is DB_PASSWORD
        - name: POSTGRESQL_HOST
          valueFrom:
            secretKeyRef:
              name: supertokens-credentials # Patched
              key: DB_HOST
        - name: POSTGRESQL_PORT
          valueFrom:
            secretKeyRef:
              name: supertokens-credentials # Patched
              key: DB_PORT
        - name: POSTGRESQL_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: supertokens-credentials # Patched
              key: DB_NAME
        # POSTGRESQL_TABLE_NAMES_PREFIX was a direct value, unaffected.

# --- Patch for Hasura Deployment ---
# Base 'hasura-secret' -> SPC 'hasura-credentials'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura-graphql-engine
  namespace: hasura
spec:
  template:
    spec:
      containers:
      - name: hasura
        env:
        # HASURA_GRAPHQL_DATABASE_URL value is "postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
        # We patch the sources of these $(...) variables.
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: hasura-credentials # Patched
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hasura-credentials # Patched
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: hasura-credentials # Patched
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: hasura-credentials # Patched
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: hasura-credentials # Patched
              key: DB_NAME
        - name: HASURA_GRAPHQL_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: hasura-credentials # Patched
              key: HASURA_GRAPHQL_JWT_SECRET
        - name: HASURA_GRAPHQL_ADMIN_SECRET
          valueFrom:
            secretKeyRef:
              name: hasura-credentials # Patched
              key: HASURA_GRAPHQL_ADMIN_SECRET
        # Other direct value env vars (HASURA_GRAPHQL_UNAUTHORIZED_ROLE, etc.) are unaffected.

# --- Patch for Optaplanner Deployment ---
# Base 'optaplanner-secret' -> SPC 'optaplanner-credentials'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: optaplanner
  namespace: optaplanner
spec:
  template:
    spec:
      containers:
      - name: optaplanner
        env:
        - name: QUARKUS_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: optaplanner-credentials # Patched
              key: POSTGRES_USER # Key in the SPC-synced K8s Secret
        - name: QUARKUS_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: optaplanner-credentials # Patched
              key: POSTGRES_PASSWORD # Key in the SPC-synced K8s Secret
        - name: PASSWORD # Optaplanner's own API auth password
          valueFrom:
            secretKeyRef:
              name: optaplanner-credentials # Patched
              key: API_TOKEN # Key in the SPC-synced K8s Secret
        # Other env vars from ConfigMap or direct value are unaffected.
