apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres # Sets the namespace for all resources in this kustomization

resources:
  - namespace.yaml
  - secret.yaml
  # - pvc.yaml # Removed, as PVC is now defined via volumeClaimTemplates in statefulset.yaml
  - statefulset.yaml
  - service.yaml

# Optional: Add common labels to all resources defined in this kustomization
# commonLabels:
#   app.kubernetes.io/name: postgresql
#   app.kubernetes.io/instance: postgres
#   app.kubernetes.io/component: database
#   app.kubernetes.io/part-of: atomic-stack # Or your specific application/project name

# Optional: Add common annotations
# commonAnnotations:
#   note: "PostgreSQL database service base configuration"
