apiVersion: v1
kind: Service
metadata:
  name: postgres-service # This name is referenced in StatefulSet's serviceName
  namespace: postgres
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: postgresql # Refers to the container port name in StatefulSet podSpec
