apiVersion: apps/v1
kind: Deployment
metadata:
  name: functions
  namespace: functions
  labels:
    app: functions
spec:
  replicas: 1 # As specified, can be scaled
  selector:
    matchLabels:
      app: functions
  template:
    metadata:
      labels:
        app: functions
    spec:
      containers:
        - name: functions
          image: "placeholder-atomic-functions:latest" # Consistent placeholder name
          imagePullPolicy: IfNotPresent # Or "Always" if using :latest frequently in dev
          ports:
            - name: main # Main application port
              containerPort: 3000 # Should match PORT in ConfigMap
              protocol: TCP
            - name: secondary # Secondary port (e.g., for WebSockets)
              containerPort: 3030 # Should match PORT_SECONDARY in ConfigMap
              protocol: TCP
          envFrom:
            - secretRef:
                name: functions-secret
            - configMapRef:
                name: functions-configmap
          # No individual 'env:' mappings here unless specific overrides or formatting are needed,
          # as most should be covered by functions-secret and functions-configmap.

          readinessProbe:
            httpGet:
              path: /healthz # Assuming a standard /healthz endpoint
              port: main    # Main port 3000
            initialDelaySeconds: 15 # Allow more time for functions service with many connections
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: main
            initialDelaySeconds: 45 # More conservative for liveness
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          # Volume mounts if needed (e.g., for temporary file storage if functions process files)
          # volumeMounts:
          #   - name: temp-storage
          #     mountPath: /tmp
      # volumes:
      #   - name: temp-storage
      #     emptyDir: {} # Example of an emptyDir volume for temporary data
