apiVersion: v1
kind: Secret
metadata:
  name: functions-secret
  namespace: functions
type: Opaque
data:
  # Authentication & Authorization
  BASIC_AUTH: YWRtaW46cGFzc3dvcmQ= # "admin:password" Placeholder for functions -admin endpoints
  HASURA_GRAPHQL_ADMIN_SECRET: bXlhZG1pbnNlY3JldGtleQ== # "myadminsecretkey" To interact with Hasura with admin rights
  API_TOKEN: cGxhY2Vob2xkZXJfdmFsdWU= # Generic API token, potentially for Optaplanner or other services

  # Cloud & AI Services
  OPENAI_API_KEY: cGxhY2Vob2xkZXJfdmFsdWU=

  # Google OAuth & Services (placeholders, ensure these are specific to the 'functions' service needs if different from 'app' or 'oauth' services)
  GOOGLE_CLIENT_ID_ANDROID: cGxhY2Vob2xkZXJfdmFsdWU=
  GOOGLE_CLIENT_ID_IOS: cGxhY2Vob2xkZXJfdmFsdWU=
  GOOGLE_CLIENT_ID_WEB: cGxhY2Vob2xkZXJfdmFsdWU=
  GOOGLE_CLIENT_SECRET_WEB: cGxhY2Vob2xkZXJfdmFsdWU=
  # GOOGLE_CLIENT_ID_ATOMIC_WEB was in previous 'functions' secret, assuming covered by general 'WEB' or distinct if needed.
  # GOOGLE_CLIENT_SECRET_ATOMIC_WEB was in previous 'functions' secret.
  GOOGLE_CALENDAR_ID: cGxhY2Vob2xkZXJfdmFsdWU=
  GOOGLE_CALENDAR_CREDENTIALS: cGxhY2Vob2xkZXJfdmFsdWU= # Base64 encoded JSON string
  GOOGLE_MAP_KEY: cGxhY2Vob2xkZXJfdmFsdWU=
  GOOGLE_PLACE_API_KEY: cGxhY2Vob2xkZXJfdmFsdWU=

  # Storage (Minio/S3)
  STORAGE_ACCESS_KEY: bWluaW9hZG1pbg== # "minioadmin" (MinIO root user for internal S3)
  STORAGE_SECRET_KEY: bWluaW8xMjM=     # "minio123" (MinIO root password)
  STORAGE_REGION: dXMtZWFzdC0x         # "us-east-1" (Example region)

  # Kafka Credentials (if functions service interacts with Kafka using SASL)
  KAFKA_USERNAME: cGxhY2Vob2xkZXJfdmFsdWU=
  KAFKA_PASSWORD: cGxhY2Vob2xkZXJfdmFsdWU=

  # OpenSearch Credentials (if functions service interacts with secured OpenSearch)
  OPENSEARCH_USERNAME: cGxhY2Vob2xkZXJfdmFsdWU=
  OPENSEARCH_PASSWORD: cGxhY2Vob2xkZXJfdmFsdWU=

  # Zoom Integration
  ZOOM_CLIENT_ID: cGxhY2Vob2xkZXJfdmFsdWU=
  ZOOM_CLIENT_SECRET: cGxhY2Vob2xkZXJfdmFsdWU=
  ZOOM_PASS_KEY: cGxhY2Vob2xkZXJfdmFsdWU=
  ZOOM_SALT_FOR_PASS: cGxhY2Vob2xkZXJfdmFsdWU=
  ZOOM_IV_FOR_PASS: cGxhY2Vob2xkZXJfdmFsdWU=
  ZOOM_WEBHOOK_SECRET_TOKEN: cGxhY2Vob2xkZXJfdmFsdWU=
  # NEXT_PUBLIC_ZOOM_CLIENT_ID is typically for frontend, if functions backend needs it, it's here from compose.

  # Optaplanner Credentials (if functions service acts as a client to Optaplanner)
  OPTAPLANNER_USERNAME: cGxhY2Vob2xkZXJfdmFsdWU= # Usually matches API_TOKEN or a specific user
  OPTAPLANNER_PASSWORD: cGxhY2Vob2xkZXJfdmFsdWU= # Usually matches API_TOKEN

  # SMTP / Email
  SMTP_HOST: cGxhY2Vob2xkZXJfdmFsdWU=
  SMTP_PORT: NTg3 # "587"
  SMTP_USER: cGxhY2Vob2xkZXJfdmFsdWU=
  SMTP_PASS: cGxhY2Vob2xkZXJfdmFsdWU=
  SMTP_FROM_EMAIL: bm9yZXBseUBleGFtcGxlLmNvbQ== # "noreply@example.com"

  # Twilio
  TWILIO_ACCOUNT_SID: cGxhY2Vob2xkZXJfdmFsdWU=
  TWILIO_AUTH_TOKEN: cGxhY2Vob2xkZXJfdmFsdWU=
  TWILIO_PHONE_NO: cGxhY2Vob2xkZXJfdmFsdWU=

  # Stripe
  STRIPE_API_KEY: cGxhY2Vob2xkZXJfdmFsdWU= # Stripe Secret Key
  STRIPE_WEBHOOK_SECRET: cGxhY2Vob2xkZXJfdmFsdWU=

  # Other External Services / Misc
  ONESIGNAL_APP_ID: cGxhY2Vob2xkZXJfdmFsdWU=
  ONESIGNAL_REST_API_KEY: cGxhY2Vob2xkZXJfdmFsdWU=
  SLACK_BOT_TOKEN: cGxhY2Vob2xkZXJfdmFsdWU=
  SLACK_SIGNING_SECRET: cGxhY2Vob2xkZXJfdmFsdWU=
  SLACK_CHANNEL_ID: cGxhY2Vob2xkZXJfdmFsdWU=

  JWT_SECRET: VGhpcyBpcyBhIHZlcnkgc2VjdXJlIGFuZCBsb25nIEpXVCBzZWNyZXQga2V5 # "This is a very secure and long JWT secret key"
  ENCRYPTION_KEY: VGhpcyBpcyBhIHZlcnkgc2VjdXJlIGFuZCBsb25nIGVuY3J5cHRpb24ga2V5 # "This is a very secure and long encryption key"
  SESSION_SECRET_KEY: U3VwZXJMb25nQW5kU2VjdXJlU2Vzc2lvblNlY3JldEtleUZvckZ1bmN0aW9ucw== # "SuperLongAndSecureSessionSecretKeyForFunctions"

  # Nhost specific variables from compose, if needed by functions directly.
  # These often alias to Hasura secrets already defined (e.g. NHOST_ADMIN_SECRET -> HASURA_GRAPHQL_ADMIN_SECRET)
  # NHOST_ADMIN_SECRET: bXlhZG1pbnNlY3JldGtleQ== # Redundant if HASURA_GRAPHQL_ADMIN_SECRET is used
  NHOST_WEBHOOK_SECRET: cGxhY2Vob2xkZXJfdmFsdWU= # If distinct from other webhook secrets
  # NHOST_JWT_SECRET: was in compose, relates to Hasura's JWT secret.

  # Ensure all sensitive values from the functions service's environment in docker-compose.yaml are listed here.
  # Using generic placeholder "cGxhY2Vob2xkZXJfdmFsdWU=" (base64 of "placeholder_value") for unspecified values.
