apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura-graphql-engine
  namespace: hasura
  labels:
    app: hasura-graphql-engine
spec:
  replicas: 1 # As specified, Hasura is stateless and can be scaled
  selector:
    matchLabels:
      app: hasura-graphql-engine
  template:
    metadata:
      labels:
        app: hasura-graphql-engine
    spec:
      containers:
        - name: hasura
          image: hasura/graphql-engine:v2.15.2 # As specified
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080 # Default Hasura port
              protocol: TCP
          env:
            # Construct HASURA_GRAPHQL_DATABASE_URL from individual secret values.
            # Hasura's entrypoint script handles this variable substitution.
            - name: HASURA_GRAPHQL_DATABASE_URL
              value: "postgres://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"

            # Source individual DB components from the secret for the URI construction above
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: hasura-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hasura-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: hasura-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: hasura-secret
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: hasura-secret
                  key: DB_NAME

            # Hasura specific secrets
            - name: HASURA_GRAPHQL_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: hasura-secret
                  key: HASURA_GRAPHQL_JWT_SECRET
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: hasura-secret
                  key: HASURA_GRAPHQL_ADMIN_SECRET

            # Other Hasura configurations from the prompt
            - name: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
              value: "public"
            - name: HASURA_GRAPHQL_LOG_LEVEL
              value: "debug"
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: "true" # Ensure this is a string 'true'

          readinessProbe:
            httpGet:
              path: /healthz # Hasura's health check endpoint
              port: http   # Port 8080
            initialDelaySeconds: 10 # Allow time for Hasura to connect to DB and start
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
