apiVersion: v1
kind: Secret
metadata:
  name: hasura-secret
  namespace: hasura
type: Opaque
data:
  # Hasura specific secrets
  HASURA_GRAPHQL_ADMIN_SECRET: bXlhZG1pbnNlY3JldGtleQ== # "myadminsecretkey"
  HASURA_GRAPHQL_JWT_SECRET: eyJ0eXBlIjoiSFMyNTYiLCJrZXkiOiJ0aGlzLWlzLWEtdmVyeS1sb25nLWFuZC1zZWN1cmUtc2VjcmV0LWtleS1mb3ItaHMyNTYiLCJjbGFpbXNfbmFtZXNwYWNlIjoiaGFzdXJhLXVzZXItY2xhaW1zIn0= # {"type":"HS256","key":"this-is-a-very-long-and-secure-secret-key-for-hs256","claims_namespace":"hasura-user-claims"}

  # PostgreSQL connection components
  DB_USER: cG9zdGdyZXM= # "postgres"
  DB_PASSWORD: c2VjcmV0cGdwYXNzd29yZA== # "secretpgpassword"
  # DB_HOST should be the address of the PostgreSQL service.
  # Assuming PostgreSQL is in 'postgres' namespace with service 'postgres-service':
  # postgres-service.postgres.svc.cluster.local
  DB_HOST: cG9zdGdyZXMtc2VydmljZS5wb3N0Z3Jlcy5zdmMuY2x1c3Rlci5sb2NhbA==
  DB_PORT: NTQzMg== # "5432"
  DB_NAME: YXRvbWljZGI= # "atomicdb"
