apiVersion: v1
kind: Service
metadata:
  name: hasura-service
  namespace: hasura
  labels:
    app: hasura-graphql-engine
spec:
  type: ClusterIP # Internal service, not exposed externally by default
  selector:
    app: hasura-graphql-engine # Selects the Hasura pods
  ports:
    - name: http
      protocol: TCP
      port: 8080       # Port the service will listen on
      targetPort: http # Matches the 'http' port name in the Deployment's podSpec (containerPort 8080)
