apiVersion: apps/v1
kind: Deployment
metadata:
  name: supertokens-core
  namespace: supertokens
  labels:
    app: supertokens-core
spec:
  replicas: 1 # As specified, can be scaled as Supertokens core is generally stateless
  selector:
    matchLabels:
      app: supertokens-core
  template:
    metadata:
      labels:
        app: supertokens-core
    spec:
      containers:
        - name: supertokens
          image: registry.supertokens.io/supertokens/supertokens-postgresql:6.0 # As specified
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3567 # Default Supertokens port
              protocol: TCP
          env:
            # Supertokens core can take individual PostgreSQL connection parameters
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: supertokens-db-secret
                  key: DB_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supertokens-db-secret
                  key: DB_PASSWORD
            - name: POSTGRESQL_HOST
              valueFrom:
                secretKeyRef:
                  name: supertokens-db-secret
                  key: DB_HOST
            - name: POSTGRESQL_PORT
              valueFrom:
                secretKeyRef:
                  name: supertokens-db-secret
                  key: DB_PORT
            - name: POSTGRESQL_DATABASE_NAME # Variable name used by Supertokens for DB name
              valueFrom:
                secretKeyRef:
                  name: supertokens-db-secret
                  key: DB_NAME
            - name: POSTGRESQL_TABLE_NAMES_PREFIX # As specified
              value: "Supertokens"
            # Optional: API Keys, etc., would also come from secrets if needed by the core
            # - name: api_keys
            #   valueFrom:
            #     secretKeyRef:
            #       name: supertokens-api-keys # A different secret for API keys
            #       key: api_keys_string

          readinessProbe:
            httpGet:
              path: /hello # Supertokens health check endpoint
              port: http   # Port 3567
            initialDelaySeconds: 10 # Allow time for Supertokens to connect to DB and start
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /hello
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
