apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: supertokens # Sets the namespace for all resources in this kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  # No ConfigMap was specified for this service in the prompt.

# Optional: Add common labels to all resources defined in this kustomization
# commonLabels:
#   app.kubernetes.io/name: supertokens
#   app.kubernetes.io/instance: supertokens-core
#   app.kubernetes.io/component: authentication
#   app.kubernetes.io/part-of: atomic-stack # Or your specific application/project name

# Optional: Add common annotations
# commonAnnotations:
#   note: "Supertokens core service base configuration"
