apiVersion: v1
kind: Secret
metadata:
  name: supertokens-db-secret # Secret containing DB connection details for Supertokens
  namespace: supertokens
type: Opaque
data:
  DB_USER: cG9zdGdyZXM= # "postgres"
  DB_PASSWORD: c2VjcmV0cGdwYXNzd29yZA== # "secretpgpassword"
  # DB_HOST should be the address of the PostgreSQL service.
  # Assuming PostgreSQL is in 'postgres' namespace with service 'postgres-service':
  DB_HOST: cG9zdGdyZXMtc2VydmljZS5wb3N0Z3Jlcy5zdmMuY2x1c3Rlci5sb2NhbA== # "postgres-service.postgres.svc.cluster.local"
  DB_PORT: NTQzMg== # "5432"
  DB_NAME: YXRvbWljZGI= # "atomicdb"
