apiVersion: v1
kind: Service
metadata:
  name: supertokens-service
  namespace: supertokens
  labels:
    app: supertokens-core
spec:
  type: ClusterIP # Internal service, not exposed externally by default
  selector:
    app: supertokens-core # Selects the Supertokens pods
  ports:
    - name: http
      protocol: TCP
      port: 3567       # Port the service will listen on
      targetPort: http # Matches the 'http' port name in the Deployment's podSpec (containerPort 3567)
