apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio # Sets the namespace for all resources in this kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

# Optional: Add common labels to all resources defined in this kustomization
# commonLabels:
#   app.kubernetes.io/name: minio
#   app.kubernetes.io/instance: minio
#   app.kubernetes.io/component: object-storage
#   app.kubernetes.io/part-of: atomic-stack # Or your specific application/project name

# Optional: Add common annotations
# commonAnnotations:
#   note: "MinIO object storage service base configuration"
