apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio

resources:
  - namespace.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

# Optional: Add common labels to all resources
# commonLabels:
#   app.kubernetes.io/name: minio
#   app.kubernetes.io/part-of: atomic-stack

# Optional: Add common annotations
# commonAnnotations:
#   source: "https://github.com/your-repo/atomic-stack"
