apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # As specified
  # storageClassName: "" # Optional: specify a storage class if needed, e.g., "do-block-storage" for DigitalOcean.
                       # For cloud provider defaults (like gp2 on AWS, standard on GKE/Azure), often not needed.
