apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio
  labels:
    app: minio
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
    - name: api
      protocol: TCP
      port: 8484
      targetPort: api
    - name: console
      protocol: TCP
      port: 9001
      targetPort: console
