apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth-configmap
  namespace: oauth
data:
  # External Application URL (where users are redirected back to)
  NEXT_PUBLIC_APP_URL: "https://${HOST_NAME}"

  # Google OAuth Redirect URL (Callback URL for this oauth service)
  GOOGLE_REDIRECT_URL: "https://${HOST_NAME}/v1/oauth/api/google-calendar-handshake/oauth2callback"

  # Handshake Service URL (Internal Kubernetes service FQDN)
  HANDSHAKE_URL: "http://handshake-service.handshake.svc.cluster.local:3000"

  # Zoom OAuth Redirect URL (Callback URL for this oauth service)
  NEXT_PUBLIC_ZOOM_REDIRECT_URL: "https://${HOST_NAME}/v1/oauth/zoom/mobile-callback"

  # Public Zoom Client ID (can be same as ZOOM_CLIENT_ID from secret, or a different public one)
  # If it's always the same as the secret one, the app could just use the env var from the secret.
  # Including it here if it's meant to be distinctly configured or explicitly public.
  NEXT_PUBLIC_ZOOM_CLIENT_ID: "YOUR_PUBLIC_ZOOM_CLIENT_ID_PLACEHOLDER"

  # Hasura GraphQL URL (if this oauth service needs to query Hasura for non-admin tasks)
  HASURA_GRAPHQL_GRAPHQL_URL: "http://hasura-service.hasura.svc.cluster.local:8080/v1/graphql"

  # Application Port for this Next.js OAuth service
  PORT: "3000"

  # Node Environment
  NODE_ENV: "production"

  # Logging Level (optional)
  # LOG_LEVEL: "info"

  # Placeholder for the external host name.
  # This value would be substituted into the URLs above by deployment automation or Ingress controller.
  HOST_NAME: "your-app-domain.com" # Example placeholder
