apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth
  namespace: oauth
  labels:
    app: oauth
spec:
  replicas: 1 # Can be scaled as Next.js standalone apps are typically stateless
  selector:
    matchLabels:
      app: oauth
  template:
    metadata:
      labels:
        app: oauth
    spec:
      containers:
        - name: oauth
          image: "${PROJECT_NAME}-atomic-oauth:latest" # Placeholder - replace with actual image URL
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000 # Matches PORT in ConfigMap
              protocol: TCP
          envFrom:
            - secretRef:
                name: oauth-secret
            - configMapRef:
                name: oauth-configmap
          # The Next.js standalone server typically listens on the port specified by the PORT env var from the ConfigMap.

          # Probes: Next.js apps in standalone mode usually serve on '/'.
          # If a specific health check endpoint is available (e.g., /api/health), use that.
          readinessProbe:
            httpGet:
              path: / # Check root path, or a specific health endpoint like /api/health
              port: http # Port 3000
            initialDelaySeconds: 10 # Allow time for Next.js server to start
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
