apiVersion: v1
kind: Secret
metadata:
  name: oauth-secret
  namespace: oauth
type: Opaque
data:
  # Zoom Secrets (as per Dockerfile ARGs)
  ZOOM_CLIENT_ID: cGxhY2Vob2xkZXJfdmFsdWU= # "placeholder_value"
  ZOOM_CLIENT_SECRET: cGxhY2Vob2xkZXJfdmFsdWU=
  ZOOM_IV_FOR_PASS: cGxhY2Vob2xkZXJfdmFsdWU=
  ZOOM_SALT_FOR_PASS: cGxhY2Vob2xkZXJfdmFsdWU=
  ZOOM_PASS_KEY: cGxhY2Vob2xkZXJfdmFsdWU=
  ZOOM_WEBHOOK_SECRET_TOKEN: cGxhY2Vob2xkZXJfdmFsdWU=

  # Google Secrets (as per Dockerfile ARGs)
  GOOGLE_CLIENT_ID_WEB: cGxhY2Vob2xkZXJfdmFsdWU=
  GOOGLE_CLIENT_SECRET_WEB: cGxhY2Vob2xkZXJfdmFsdWU=

  # Hasura Admin Secret (as per Dockerfile ARGs)
  HASURA_GRAPHQL_ADMIN_SECRET: bXlhZG1pbnNlY3JldGtleQ== # "myadminsecretkey"

  # Session Secret for this OAuth service
  SESSION_SECRET_KEY: U3VwZXJMb25nQW5kU2VjdXJlU2Vzc2lvblNlY3JldEtleUZvck9BdXRoU2VydmljZQ== # "SuperLongAndSecureSessionSecretKeyForOAuthService"

  # Any other sensitive variables identified from ARGs or runtime needs for the oauth service.
  # Ensure all ARGs from the Dockerfile that are sensitive are listed here.
