apiVersion: v1
kind: Secret
metadata:
  name: oauth-secret
  namespace: oauth
type: Opaque
data:
  # Zoom Secrets
  ZOOM_CLIENT_ID: cGxhY2Vob2xkZXJfdmFsdWU= # "placeholder_value"
  ZOOM_CLIENT_SECRET: cGxhY2Vob2xkZXJfdmFsdWU=
  ZOOM_IV_FOR_PASS: cGxhY2Vob2xkZXJfdmFsdWU=
  ZOOM_SALT_FOR_PASS: cGxhY2Vob2xkZXJfdmFsdWU=
  ZOOM_PASS_KEY: cGxhY2Vob2xkZXJfdmFsdWU=
  ZOOM_WEBHOOK_SECRET_TOKEN: cGxhY2Vob2xkZXJfdmFsdWU=

  # Google Secrets
  GOOGLE_CLIENT_ID_WEB: cGxhY2Vob2xkZXJfdmFsdWU=
  GOOGLE_CLIENT_SECRET_WEB: cGxhY2Vob2xkZXJfdmFsdWU=

  # Hasura Admin Secret (if direct privileged access is needed)
  HASURA_GRAPHQL_ADMIN_SECRET: bXlhZG1pbnNlY3JldGtleQ== # "myadminsecretkey" (ensure this matches Hasura's actual admin secret)

  # Any other sensitive variables derived from ARGs or runtime needs
  # For example, a session secret for the oauth service itself
  SESSION_SECRET_KEY: MlYzM0JsNVBUbUZuZFdGMFpYTXRZbVZrYzJsd0oyeHNiM2RmWlc1aGJDZ25jbTlzYkdsdw== # "SuperLongAndSecureSessionSecretKeyForOAuthService"
