apiVersion: v1
kind: Service
metadata:
  name: oauth-service
  namespace: oauth
  labels:
    app: oauth
spec:
  type: ClusterIP # Internal service
  selector:
    app: oauth # Selects the oauth pods
  ports:
    - name: http
      protocol: TCP
      port: 3000       # Port the service will listen on
      targetPort: http # Matches the 'http' port name in the Deployment's podSpec (containerPort 3000)
