apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
  labels:
    app: kafka
spec:
  serviceName: "kafka-headless" # Must match the headless Service name
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 30 # Kafka can take longer to shutdown cleanly
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:5.4.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: internal
              containerPort: 9092 # Port for internal cluster communication and default client access
              protocol: TCP
            # Port 29092 was mentioned for external, but for ClusterIP, 9092 is primary.
            # If NodePort or LoadBalancer were used, 29092 might be configured for external access.
          env:
            - name: KAFKA_BROKER_ID
              value: "0" # For a single broker setup, ID 0 is typical
            - name: KAFKA_ZOOKEEPER_CONNECT
              # Assumes zookeeper-service is resolvable in the same namespace.
              # For cross-namespace, use FQDN: zookeeper-service.kafka.svc.cluster.local:2181
              value: "zookeeper-service:2181"
            # Listeners: PLAINTEXT within the cluster.
            # The advertised listener needs to be the address clients use.
            # For in-cluster access via the headless service FQDN for the pod:
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              # kafka-0 is the pod name, kafka-headless is the service name, kafka is the namespace
              value: "PLAINTEXT://kafka-0.kafka-headless.kafka.svc.cluster.local:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1" # For single broker cluster
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_LOG_DIRS # Directory where Kafka data logs are stored
              value: "/var/lib/kafka/data/logs" # Standard location within the volume
            # Additional recommended settings for single node / dev:
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_NUM_PARTITIONS
              value: "1" # Default for auto-created topics
            # Control plane listener (new in some Kafka versions, good practice for Confluent)
            # - name: KAFKA_CONTROL_PLANE_LISTENER_NAME
            #   value: "CONTROL_PLANE"
            # - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            #   value: "PLAINTEXT:PLAINTEXT,CONTROL_PLANE:PLAINTEXT"
            # - name: KAFKA_LISTENERS
            #   value: "PLAINTEXT://:9092,CONTROL_PLANE://:9091" # Example if control plane listener is used

          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          # Liveness probe can be tricky for Kafka, often omitted or made less aggressive.
          # A simple TCP check can indicate if the broker process is up.
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-data-pvc
