apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
  labels:
    app: kafka
spec:
  serviceName: "kafka-headless" # Must match the headless Service name
  replicas: 1 # For base simplicity
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 30 # Kafka can take time to shut down cleanly
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:5.4.2 # As specified
          imagePullPolicy: IfNotPresent
          ports:
            - name: internal # PLAINTEXT port for internal communication and clients
              containerPort: 9092
              protocol: TCP
          env:
            - name: KAFKA_BROKER_ID
              value: "0" # For a single broker, ID 0 is typical
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service.kafka.svc.cluster.local:2181" # FQDN for Zookeeper service
            - name: KAFKA_LISTENERS # Listener within the pod network
              value: "PLAINTEXT://:9092"
            - name: KAFKA_ADVERTISED_LISTENERS # How clients connect to this specific broker
                                              # Uses the pod's FQDN: kafka-0.kafka-headless.kafka.svc.cluster.local
              value: "PLAINTEXT://kafka-0.kafka-headless.kafka.svc.cluster.local:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1" # For a single broker cluster
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_LOG_DIRS # Directory where Kafka data logs are stored
              value: "/var/lib/kafka/data/logs" # Standard location within the mounted volume
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR # For auto-created topics
              value: "1"
            - name: KAFKA_NUM_PARTITIONS # Default partitions for auto-created topics
              value: "1"
            # Confluent specific variables for control center, etc. (can be omitted for base)
            # KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: "1"
            # KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: "1"
            # KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
            # KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
          volumeMounts:
            - name: kafka-data # Corresponds to volumeClaimTemplates.metadata.name
              mountPath: /var/lib/kafka/data
          readinessProbe:
            tcpSocket:
              port: internal # Port 9092
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: internal
            initialDelaySeconds: 60 # Give more time for Kafka to start before liveness checks
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
  volumeClaimTemplates:
  - metadata:
      name: kafka-data # Name for the data PVC template
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi # As specified
      # storageClassName: "your-storage-class" # Optional
