# Headless service for Kafka broker pod discovery (DNS records like kafka-0.kafka-headless.kafka.svc.cluster.local)
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: kafka
  labels:
    app: kafka
spec:
  clusterIP: None # Defines the service as headless
  selector:
    app: kafka # Selects the Kafka pods
  ports:
    - name: internal # Port for broker-to-broker or direct pod access if needed
      port: 9092
      targetPort: internal # Matches 'internal' port name in Kafka StatefulSet

---
# ClusterIP service for Kafka clients (applications connecting to Kafka broker)
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
  labels:
    app: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka # Selects the Kafka pods
  ports:
    - name: client # Port for clients to connect to Kafka
      protocol: TCP
      port: 9092       # External port clients connect to (service port)
      targetPort: internal # Target port on the Kafka pods (containerPort name 'internal', which is 9092)
