# Headless service for Zookeeper pod discovery (DNS records for zookeeper-0.zookeeper-headless.kafka.svc.cluster.local)
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
  namespace: kafka
  labels:
    app: zookeeper
spec:
  clusterIP: None # Defines the service as headless
  selector:
    app: zookeeper
  ports:
    - name: server
      port: 2888
      targetPort: server
    - name: leader-election
      port: 3888
      targetPort: leader-election

---
# ClusterIP service for Zookeeper clients
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: kafka
  labels:
    app: zookeeper
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
    - name: client
      protocol: TCP
      port: 2181
      targetPort: client
