apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: kafka
  labels:
    app: zookeeper
spec:
  serviceName: "zookeeper-headless" # Must match the headless Service name
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:5.4.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: client
              containerPort: 2181
              protocol: TCP
            - name: server
              containerPort: 2888
              protocol: TCP
            - name: leader-election
              containerPort: 3888
              protocol: TCP
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_DATA_DIR
              value: "/var/lib/zookeeper/data"
            - name: ZOOKEEPER_LOG_DIR # Note: confluent images might use ZOOKEEPER_DATA_LOG_DIR or just log to data dir by default.
              value: "/var/lib/zookeeper/log" # Explicitly setting log dir.
            # For single node, server ID is typically 1
            - name: ZOOKEEPER_SERVER_ID
              value: "1"
            # For single node, servers list is just itself
            - name: ZOOKEEPER_SERVERS
              value: "zookeeper-0.zookeeper-headless.kafka.svc.cluster.local:2888:3888"


          volumeMounts:
            - name: zookeeper-data
              mountPath: /var/lib/zookeeper/data
            - name: zookeeper-log
              mountPath: /var/lib/zookeeper/log
          readinessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "echo ruok | nc localhost 2181 | grep imok"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "echo ruok | nc localhost 2181 | grep imok"
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: zookeeper-data
          persistentVolumeClaim:
            claimName: zookeeper-data-pvc
        - name: zookeeper-log
          persistentVolumeClaim:
            claimName: zookeeper-log-pvc
