apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik-ingress # Sets the namespace for all resources in this kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - ingressclass.yaml
  # Add other Traefik related resources here if needed, e.g.,
  # - configmap.yaml # If you have a separate Traefik static config in a ConfigMap
  # - pvc.yaml       # If you need a PersistentVolumeClaim for ACME certs (and uncommented in deployment)

# Optional: Add common labels to all resources defined in this kustomization
# commonLabels:
#   app.kubernetes.io/managed-by: kustomize
#   app.kubernetes.io/component: ingress-controller

# Optional: Add common annotations
# commonAnnotations:
#   note: "Traefik Ingress Controller base configuration"
