apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: handshake # Sets the namespace for all resources in this kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

# Optional: Add common labels to all resources defined in this kustomization
# commonLabels:
#   app.kubernetes.io/name: handshake
#   app.kubernetes.io/instance: handshake
#   app.kubernetes.io/component: frontend-api # Or as appropriate
#   app.kubernetes.io/part-of: atomic-stack

# Optional: Add common annotations
# commonAnnotations:
#   note: "Handshake service base configuration"
