apiVersion: v1
kind: Secret
metadata:
  name: handshake-secret
  namespace: handshake
type: Opaque
data:
  # API_TOKEN for authenticating with other backend services if needed by Handshake service
  API_TOKEN: aGFuZHNoYWtlX2FwaV90b2tlbl9wbGFjZWhvbGRlcg== # "handshake_api_token_placeholder"

  # HASURA_GRAPHQL_ADMIN_SECRET for privileged operations against Hasura, if Handshake service needs it directly.
  # This was identified as a Dockerfile ARG for this service.
  HASURA_GRAPHQL_ADMIN_SECRET: bXlhZG1pbnNlY3JldGtleQ== # "myadminsecretkey" (ensure this matches Hasura's actual admin secret)
