apiVersion: v1
kind: Service
metadata:
  name: handshake-service
  namespace: handshake
  labels:
    app: handshake
spec:
  type: ClusterIP
  selector:
    app: handshake # Selects the handshake pods
  ports:
    - name: http
      protocol: TCP
      port: 3000 # Port the service will listen on
      targetPort: http # Name of the port in the Deployment's podSpec (containerPort 3000)
