apiVersion: v1
kind: Service
metadata:
  name: handshake-service
  namespace: handshake
  labels:
    app: handshake
spec:
  type: ClusterIP # Internal service
  selector:
    app: handshake # Selects the handshake pods
  ports:
    - name: http
      protocol: TCP
      port: 3000       # Port the service will listen on
      targetPort: http # Matches the 'http' port name in the Deployment's podSpec (containerPort 3000)
