# ClusterIP Service for client connections to OpenSearch (HTTP REST API)
apiVersion: v1
kind: Service
metadata:
  name: opensearch-service
  namespace: opensearch
  labels:
    app: opensearch
spec:
  type: ClusterIP
  selector:
    app: opensearch # Selects the OpenSearch pods managed by the StatefulSet
  ports:
    - name: http # For REST API
      protocol: TCP
      port: 9200       # Port the service will listen on
      targetPort: http # Matches the 'http' port name in the StatefulSet's podSpec (containerPort 9200)
    - name: transport # For node-to-node communication (though less relevant for single node, good practice to define)
      protocol: TCP
      port: 9600       # Port the service will listen on for transport
      targetPort: transport # Matches the 'transport' port name in the StatefulSet's podSpec (containerPort 9600)

---
# Headless Service for OpenSearch StatefulSet pod discovery
# Provides stable DNS records for each pod (e.g., opensearch-0.opensearch-headless.opensearch.svc.cluster.local)
apiVersion: v1
kind: Service
metadata:
  name: opensearch-headless
  namespace: opensearch
  labels:
    app: opensearch
spec:
  clusterIP: None # Defines the service as headless
  selector:
    app: opensearch # Selects the OpenSearch pods
  ports:
    - name: http # Exposing http port here as well, though opensearch-service is primary for clients
      port: 9200
      targetPort: http
    - name: transport # For node-to-node communication, essential for multi-node discovery via headless service
      protocol: TCP
      port: 9600
      targetPort: transport
