apiVersion: apps/v1
kind: Deployment
metadata:
  name: optaplanner
  namespace: optaplanner
  labels:
    app: optaplanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: optaplanner
  template:
    metadata:
      labels:
        app: optaplanner
    spec:
      containers:
        - name: optaplanner
          image: "${PROJECT_NAME}-atomic-scheduler:latest" # Placeholder - replace with actual image URL
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081 # Matches QUARKUS_HTTP_PORT in ConfigMap
              protocol: TCP
          env:
            # Quarkus Datasource credentials from Secret
            - name: QUARKUS_DATASOURCE_USERNAME # User for DB connection
              valueFrom:
                secretKeyRef:
                  name: optaplanner-secret
                  key: POSTGRES_USER
            - name: QUARKUS_DATASOURCE_PASSWORD # Password for DB connection
              valueFrom:
                secretKeyRef:
                  name: optaplanner-secret
                  key: POSTGRES_PASSWORD

            # Optaplanner application's own API authentication password from Secret
            - name: PASSWORD # Used by Optaplanner for its /api basic auth or token auth
              valueFrom:
                secretKeyRef:
                  name: optaplanner-secret
                  key: API_TOKEN

            # Other datasource and app config from ConfigMap
            - name: QUARKUS_DATASOURCE_JDBC_URL
              valueFrom:
                configMapKeyRef:
                  name: optaplanner-configmap
                  key: QUARKUS_DATASOURCE_JDBC_URL
            - name: QUARKUS_DATASOURCE_DB-KIND
              valueFrom:
                configMapKeyRef:
                  name: optaplanner-configmap
                  key: QUARKUS_DATASOURCE_DB-KIND
            # Note: The username for the datasource is taken from POSTGRES_USER secret directly
            # The USERNAME in configmap was intended for this, but Quarkus expects QUARKUS_DATASOURCE_USERNAME.
            # So, we map POSTGRES_USER from secret to QUARKUS_DATASOURCE_USERNAME.
            # If Optaplanner app has a separate internal "admin" user concept (not DB user),
            # that would be configured differently, e.g. with app-specific properties.
            # The prompt's configmap had USERNAME: admin, but for datasource, it must match the actual DB user.

            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: optaplanner-configmap
                  key: QUARKUS_HTTP_PORT
            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: optaplanner-configmap
                  key: QUARKUS_LOG_LEVEL

            # If DB_HOST, DB_PORT, DB_NAME are needed by the app to construct the JDBC URL itself:
            # - name: DB_HOST
            #   valueFrom:
            #     configMapKeyRef:
            #       name: optaplanner-configmap
            #       key: DB_HOST
            # - name: DB_PORT
            #   valueFrom:
            #     configMapKeyRef:
            #       name: optaplanner-configmap
            #       key: DB_PORT
            # - name: DB_NAME
            #   valueFrom:
            #     configMapKeyRef:
            #       name: optaplanner-configmap
            #       key: DB_NAME

          readinessProbe:
            httpGet:
              path: /q/health/ready # Standard Quarkus readiness probe
              port: http # Port 8081
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /q/health/live # Standard Quarkus liveness probe
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
