apiVersion: apps/v1
kind: Deployment
metadata:
  name: optaplanner
  namespace: optaplanner
  labels:
    app: optaplanner
spec:
  replicas: 1 # As specified
  selector:
    matchLabels:
      app: optaplanner
  template:
    metadata:
      labels:
        app: optaplanner
    spec:
      containers:
        - name: optaplanner
          image: "placeholder-atomic-scheduler:latest" # Consistent placeholder name
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081 # Should match QUARKUS_HTTP_PORT from ConfigMap
              protocol: TCP
          env:
            # Database credentials from Secret
            - name: QUARKUS_DATASOURCE_USERNAME # For Quarkus to connect to the DB
              valueFrom:
                secretKeyRef:
                  name: optaplanner-secret
                  key: POSTGRES_USER
            - name: QUARKUS_DATASOURCE_PASSWORD # For Quarkus to connect to the DB
              valueFrom:
                secretKeyRef:
                  name: optaplanner-secret
                  key: POSTGRES_PASSWORD

            # Optaplanner application's own authentication credentials
            # USERNAME is from ConfigMap, PASSWORD is from API_TOKEN in Secret
            - name: USERNAME # For Optaplanner application auth
              valueFrom:
                configMapKeyRef:
                  name: optaplanner-configmap
                  key: USERNAME
            - name: PASSWORD # For Optaplanner application auth (maps to API_TOKEN from secret)
              valueFrom:
                secretKeyRef:
                  name: optaplanner-secret
                  key: API_TOKEN

            # Other configurations from ConfigMap
            - name: QUARKUS_DATASOURCE_JDBC_URL
              valueFrom:
                configMapKeyRef:
                  name: optaplanner-configmap
                  key: QUARKUS_DATASOURCE_JDBC_URL
            - name: QUARKUS_DATASOURCE_DB-KIND
              valueFrom:
                configMapKeyRef:
                  name: optaplanner-configmap
                  key: QUARKUS_DATASOURCE_DB-KIND
            - name: QUARKUS_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: optaplanner-configmap
                  key: QUARKUS_HTTP_PORT
            - name: QUARKUS_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: optaplanner-configmap
                  key: QUARKUS_LOG_LEVEL
            # Add other env vars from configmap if needed (e.g., QUARKUS_OPTAPLANNER_...)

          readinessProbe:
            httpGet:
              path: /q/health/ready # Standard Quarkus readiness probe
              port: http # Port 8081
            initialDelaySeconds: 15 # Allow time for Quarkus app to start and connect to DB
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /q/health/live # Standard Quarkus liveness probe
              port: http
            initialDelaySeconds: 45 # More conservative for liveness
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
