apiVersion: v1
kind: Secret
metadata:
  name: optaplanner-secret
  namespace: optaplanner
type: Opaque
data:
  # PostgreSQL credentials for Optaplanner's datasource
  POSTGRES_USER: cG9zdGdyZXM= # "postgres"
  POSTGRES_PASSWORD: c2VjcmV0cGdwYXNzd29yZA== # "secretpgpassword"

  # API_TOKEN for Optaplanner's own security (will be mapped to PASSWORD env var for the app)
  # Also used by 'functions' service to authenticate with Optaplanner.
  API_TOKEN: b3B0YXBsYW5uZXJfYXBpX3Rva2VuX3BsYWNlaG9sZGVy # "optaplanner_api_token_placeholder"
