apiVersion: v1
kind: Secret
metadata:
  name: optaplanner-secret
  namespace: optaplanner
type: Opaque
data:
  # PostgreSQL credentials for Optaplanner's datasource
  POSTGRES_USER: cG9zdGdyZXM= # "postgres"
  POSTGRES_PASSWORD: c2VjcmV0cGdwYXNzd29yZA== # "secretpgpassword"

  # API_TOKEN for Optaplanner's own security.
  # This will be mapped to the 'PASSWORD' env var in the deployment for the application's auth.
  API_TOKEN: b3B0YXBsYW5uZXJfYXBpX3Rva2VuX3BsYWNlaG9sZGVy # "optaplanner_api_token_placeholder"
