apiVersion: v1
kind: Service
metadata:
  name: optaplanner-service
  namespace: optaplanner
  labels:
    app: optaplanner
spec:
  type: ClusterIP
  selector:
    app: optaplanner # Selects the optaplanner pods
  ports:
    - name: http
      protocol: TCP
      port: 8081 # Port the service will listen on
      targetPort: http # Name of the port in the Deployment's podSpec (containerPort 8081)
