apiVersion: v1
kind: Service
metadata:
  name: optaplanner-service
  namespace: optaplanner
  labels:
    app: optaplanner
spec:
  type: ClusterIP # Internal service
  selector:
    app: optaplanner # Selects the Optaplanner pods
  ports:
    - name: http
      protocol: TCP
      port: 8081       # Port the service will listen on
      targetPort: http # Matches the 'http' port name in the Deployment's podSpec (containerPort 8081)
